import { ReactSelectData } from "../components/FilterDrawer";

export const diets: ReactSelectData[] = [
  { value: "gluten free", label: "Gluten Free" },
  { value: "ketogenic", label: "Ketogenic" },
  { value: "paleo", label: "Paleo" },
  { value: "pescetarian", label: "Pescetarian" },
  { value: "vegan", label: "Vegan" },
  { value: "vegetarian", label: "Vegetarian" },
];

export const intolerances: ReactSelectData[] = [
  { value: "dairy", label: "Dairy" },
  { value: "egg", label: "Egg" },
  { value: "gluten", label: "Gluten" },
  { value: "peanut", label: "Peanut" },
  { value: "seafood", label: "Seafood" },
  { value: "sesame", label: "Sesame" },
  { value: "soy", label: "Soy" },
];

export const ingredients: ReactSelectData[] = [
  { value: "acorn squash", label: "Acorn squash" },
  { value: "agave nectar", label: "Agave nectar" },
  { value: "alfredo pasta sauce", label: "Alfredo pasta sauce" },
  { value: "almond flour", label: "Almond flour" },
  { value: "almond milk", label: "Almond milk" },
  { value: "almonds", label: "Almonds" },
  { value: "amaretto", label: "Amaretto" },
  { value: "anchovies", label: "Anchovies" },
  { value: "apple", label: "Apple" },
  { value: "apple cider", label: "Apple cider" },
  { value: "apple juice", label: "Apple juice" },
  { value: "apricot preserves", label: "Apricot preserves" },
  { value: "apricots", label: "Apricots" },
  { value: "arborio rice", label: "Arborio rice" },
  { value: "arrowroot powder", label: "Arrowroot powder" },
  { value: "artichokes", label: "Artichokes" },
  { value: "arugula", label: "Arugula" },
  { value: "asafoetida", label: "Asafoetida" },
  { value: "asiago cheese", label: "Asiago cheese" },
  { value: "asian pear", label: "Asian pear" },
  { value: "asparagus spears", label: "Asparagus spears" },
  { value: "avocado", label: "Avocado" },
  { value: "baby bok choy", label: "Baby bok choy" },
  { value: "baby carrots", label: "Baby carrots" },
  { value: "baby corn", label: "Baby corn" },
  { value: "bacon", label: "Bacon" },
  { value: "bacon fat", label: "Bacon fat" },
  { value: "baguette", label: "Baguette" },
  { value: "baking powder", label: "Baking powder" },
  { value: "baking soda", label: "Baking soda" },
  { value: "balsamic glaze", label: "Balsamic glaze" },
  { value: "balsamic vinegar", label: "Balsamic vinegar" },
  { value: "bamboo shoots", label: "Bamboo shoots" },
  { value: "banana", label: "Banana" },
  { value: "basmati rice", label: "Basmati rice" },
  { value: "bay leaves", label: "Bay leaves" },
  { value: "bbq sauce", label: "Bbq sauce" },
  { value: "beef", label: "Beef" },
  { value: "beef brisket", label: "Beef brisket" },
  { value: "beef chuck roast", label: "Beef chuck roast" },
  { value: "beef stock", label: "Beef stock" },
  { value: "beef tenderloin", label: "Beef tenderloin" },
  { value: "beer", label: "Beer" },
  { value: "beets", label: "Beets" },
  { value: "bell pepper", label: "Bell pepper" },
  { value: "biscuits", label: "Biscuits" },
  { value: "black beans", label: "Black beans" },
  { value: "black olives", label: "Black olives" },
  { value: "black pepper", label: "Black pepper" },
  { value: "black sesame seeds", label: "Black sesame seeds" },
  { value: "blackberries", label: "Blackberries" },
  { value: "blue cheese", label: "Blue cheese" },
  { value: "blueberries", label: "Blueberries" },
  { value: "bok choy", label: "Bok choy" },
  { value: "bourbon", label: "Bourbon" },
  { value: "brandy", label: "Brandy" },
  { value: "bread", label: "Bread" },
  { value: "brie", label: "Brie" },
  { value: "broccoli", label: "Broccoli" },
  { value: "brown rice", label: "Brown rice" },
  { value: "brown rice flour", label: "Brown rice flour" },
  { value: "brown sugar", label: "Brown sugar" },
  { value: "brussel sprouts", label: "Brussel sprouts" },
  { value: "bulgur", label: "Bulgur" },
  { value: "butter", label: "Butter" },
  { value: "buttermilk", label: "Buttermilk" },
  { value: "butternut squash", label: "Butternut squash" },
  { value: "butterscotch chips", label: "Butterscotch chips" },
  { value: "cabbage", label: "Cabbage" },
  { value: "candy canes", label: "Candy canes" },
  { value: "canned black beans", label: "Canned black beans" },
  { value: "canned diced tomatoes", label: "Canned diced tomatoes" },
  { value: "canned garbanzo beans", label: "Canned garbanzo beans" },
  { value: "canned green chiles", label: "Canned green chiles" },
  { value: "canned kidney beans", label: "Canned kidney beans" },
  { value: "canned mushrooms", label: "Canned mushrooms" },
  { value: "canned pinto beans", label: "Canned pinto beans" },
  { value: "canned red kidney beans", label: "Canned red kidney beans" },
  { value: "canned tomatoes", label: "Canned tomatoes" },
  { value: "canned tuna", label: "Canned tuna" },
  { value: "canned white beans", label: "Canned white beans" },
  { value: "cannellini beans", label: "Cannellini beans" },
  { value: "cantaloupe", label: "Cantaloupe" },
  { value: "capers", label: "Capers" },
  { value: "caramel sauce", label: "Caramel sauce" },
  { value: "cardamom", label: "Cardamom" },
  { value: "cardamom pods", label: "Cardamom pods" },
  { value: "carp", label: "Carp" },
  { value: "carrots", label: "Carrots" },
  { value: "cauliflower", label: "Cauliflower" },
  { value: "celery", label: "Celery" },
  { value: "champagne", label: "Champagne" },
  { value: "cheddar", label: "Cheddar" },
  { value: "cheese", label: "Cheese" },
  { value: "cherry", label: "Cherry" },
  { value: "cherry tomatoes", label: "Cherry tomatoes" },
  { value: "chestnuts", label: "Chestnuts" },
  { value: "chia seeds", label: "Chia seeds" },
  { value: "chicken bouillon", label: "Chicken bouillon" },
  { value: "chicken breasts", label: "Chicken breasts" },
  { value: "chicken broth", label: "Chicken broth" },
  { value: "chicken legs", label: "Chicken legs" },
  { value: "chicken sausage", label: "Chicken sausage" },
  { value: "chicken stock", label: "Chicken stock" },
  { value: "chicken thighs", label: "Chicken thighs" },
  { value: "chicken wings", label: "Chicken wings" },
  { value: "chickpea", label: "Chickpea" },
  { value: "chili paste", label: "Chili paste" },
  { value: "chili peppers", label: "Chili peppers" },
  { value: "chili powder", label: "Chili powder" },
  { value: "chili sauce", label: "Chili sauce" },
  { value: "chocolate", label: "Chocolate" },
  { value: "chocolate chip cookies", label: "Chocolate chip cookies" },
  { value: "chocolate milk", label: "Chocolate milk" },
  { value: "chocolate syrup", label: "Chocolate syrup" },
  { value: "chorizo sausage", label: "Chorizo sausage" },
  { value: "cilantro", label: "Cilantro" },
  { value: "cinnamon roll", label: "Cinnamon roll" },
  { value: "cinnamon stick", label: "Cinnamon stick" },
  { value: "cinnamon sugar", label: "Cinnamon sugar" },
  { value: "cinnamon swirl bread", label: "Cinnamon swirl bread" },
  { value: "clam juice", label: "Clam juice" },
  { value: "clams", label: "Clams" },
  { value: "clarified butter", label: "Clarified butter" },
  { value: "clove", label: "Clove" },
  { value: "coarse salt", label: "Coarse salt" },
  { value: "coarsely ground pepper", label: "Coarsely ground pepper" },
  { value: "cocoa nibs", label: "Cocoa nibs" },
  { value: "cocoa powder", label: "Cocoa powder" },
  { value: "coconut", label: "Coconut" },
  { value: "coconut aminos", label: "Coconut aminos" },
  { value: "coconut butter", label: "Coconut butter" },
  { value: "coconut cream", label: "Coconut cream" },
  { value: "coconut extract", label: "Coconut extract" },
  { value: "coconut flour", label: "Coconut flour" },
  { value: "coconut milk", label: "Coconut milk" },
  { value: "coconut oil", label: "Coconut oil" },
  { value: "coconut water", label: "Coconut water" },
  { value: "cod", label: "Cod" },
  { value: "coffee", label: "Coffee" },
  { value: "cognac", label: "Cognac" },
  { value: "cola", label: "Cola" },
  { value: "colby jack", label: "Colby jack" },
  { value: "collard greens", label: "Collard greens" },
  { value: "confectioner's swerve", label: "Confectioner's swerve" },
  { value: "cooked bacon", label: "Cooked bacon" },
  { value: "cooked brown rice", label: "Cooked brown rice" },
  { value: "cooked chicken breast", label: "Cooked chicken breast" },
  { value: "cooked ham", label: "Cooked ham" },
  { value: "cooked long grain rice", label: "Cooked long grain rice" },
  { value: "cooked pasta", label: "Cooked pasta" },
  { value: "cooked polenta", label: "Cooked polenta" },
  { value: "cooked quinoa", label: "Cooked quinoa" },
  { value: "cooked wild rice", label: "Cooked wild rice" },
  { value: "cookies", label: "Cookies" },
  { value: "coriander", label: "Coriander" },
  { value: "corn", label: "Corn" },
  { value: "corn chips", label: "Corn chips" },
  { value: "corn flakes cereal", label: "Corn flakes cereal" },
  { value: "corn flour", label: "Corn flour" },
  { value: "corn kernels", label: "Corn kernels" },
  { value: "corn oil", label: "Corn oil" },
  { value: "corn tortillas", label: "Corn tortillas" },
  { value: "cornbread", label: "Cornbread" },
  { value: "corned beef", label: "Corned beef" },
  { value: "cornish hens", label: "Cornish hens" },
  { value: "cornmeal", label: "Cornmeal" },
  { value: "cornstarch", label: "Cornstarch" },
  { value: "cotija cheese", label: "Cotija cheese" },
  { value: "cottage cheese", label: "Cottage cheese" },
  { value: "country bread", label: "Country bread" },
  { value: "courgettes", label: "Courgettes" },
  { value: "couscous", label: "Couscous" },
  { value: "cow pea", label: "Cow pea" },
  { value: "crabmeat", label: "Crabmeat" },
  { value: "cracked pepper", label: "Cracked pepper" },
  { value: "cranberries", label: "Cranberries" },
  { value: "cranberry juice", label: "Cranberry juice" },
  { value: "cream", label: "Cream" },
  { value: "cream cheese", label: "Cream cheese" },
  { value: "cream cheese block", label: "Cream cheese block" },
  { value: "cream of chicken soup", label: "Cream of chicken soup" },
  { value: "cream of tartar", label: "Cream of tartar" },
  { value: "creamed corn", label: "Creamed corn" },
  { value: "creamy peanut butter", label: "Creamy peanut butter" },
  { value: "creme fraiche", label: "Creme fraiche" },
  { value: "cremini mushrooms", label: "Cremini mushrooms" },
  { value: "creole seasoning", label: "Creole seasoning" },
  { value: "crisp rice cereal", label: "Crisp rice cereal" },
  { value: "croutons", label: "Croutons" },
  { value: "crystallized ginger", label: "Crystallized ginger" },
  { value: "cucumber", label: "Cucumber" },
  { value: "cumin seeds", label: "Cumin seeds" },
  { value: "cup cake", label: "Cup cake" },
  { value: "currants", label: "Currants" },
  { value: "curry leaves", label: "Curry leaves" },
  { value: "dairy free milk", label: "Dairy free milk" },
  { value: "dark brown sugar", label: "Dark brown sugar" },
  { value: "dark chocolate", label: "Dark chocolate" },
  { value: "dark sesame oil", label: "Dark sesame oil" },
  { value: "dates", label: "Dates" },
  { value: "deep dish pie crust", label: "Deep dish pie crust" },
  { value: "deli ham", label: "Deli ham" },
  { value: "deli turkey", label: "Deli turkey" },
  { value: "dessert oats", label: "Dessert oats" },
  { value: "dessert wine", label: "Dessert wine" },
  { value: "diced ham", label: "Diced ham" },
  { value: "diet pop", label: "Diet pop" },
  { value: "dijon mustard", label: "Dijon mustard" },
  { value: "dill", label: "Dill" },
  { value: "dill pickles", label: "Dill pickles" },
  { value: "hot dog", label: "Hot dog" },
  { value: "double cream", label: "Double cream" },
  { value: "dried apricots", label: "Dried apricots" },
  { value: "dried basil", label: "Dried basil" },
  { value: "dried cherries", label: "Dried cherries" },
  { value: "dried chorizo", label: "Dried chorizo" },
  { value: "dried cranberries", label: "Dried cranberries" },
  { value: "dried dill", label: "Dried dill" },
  { value: "dried onion", label: "Dried onion" },
  { value: "dried porcini mushrooms", label: "Dried porcini mushrooms" },
  { value: "dried rubbed sage", label: "Dried rubbed sage" },
  { value: "dried thyme", label: "Dried thyme" },
  { value: "dried tomatoes", label: "Dried tomatoes" },
  { value: "dry bread crumbs", label: "Dry bread crumbs" },
  { value: "dry milk", label: "Dry milk" },
  { value: "dry mustard", label: "Dry mustard" },
  { value: "dry red wine", label: "Dry red wine" },
  { value: "dry roasted peanuts", label: "Dry roasted peanuts" },
  { value: "duck fat", label: "Duck fat" },
  { value: "dutch process cocoa powder", label: "Dutch process cocoa powder" },
  { value: "edamame", label: "Edamame" },
  { value: "egg substitute", label: "Egg substitute" },
  { value: "egg vermicelli", label: "Egg vermicelli" },
  { value: "egg whites", label: "Egg whites" },
  { value: "egg yolk", label: "Egg yolk" },
  { value: "eggnog", label: "Eggnog" },
  { value: "eggplant", label: "Eggplant" },
  { value: "elbow macaroni", label: "Elbow macaroni" },
  { value: "enchilada sauce", label: "Enchilada sauce" },
  { value: "english cucumber", label: "English cucumber" },
  { value: "english muffin", label: "English muffin" },
  { value: "erythritol", label: "Erythritol" },
  { value: "escarole", label: "Escarole" },
  { value: "espresso", label: "Espresso" },
  { value: "evaporated milk", label: "Evaporated milk" },
  { value: "extra firm tofu", label: "Extra firm tofu" },
  { value: "extra virgin olive oil", label: "Extra virgin olive oil" },
  { value: "farfalle", label: "Farfalle" },
  { value: "farro", label: "Farro" },
  { value: "fat free mayo", label: "Fat free mayo" },
  {
    value: "fat-free less-sodium chicken broth",
    label: "Fat-free less-sodium chicken broth",
  },
  { value: "fennel", label: "Fennel" },
  { value: "fennel seeds", label: "Fennel seeds" },
  { value: "fenugreek leaf", label: "Fenugreek leaf" },
  { value: "fenugreek seeds", label: "Fenugreek seeds" },
  { value: "feta cheese", label: "Feta cheese" },
  { value: "fettuccine", label: "Fettuccine" },
  { value: "fire roasted tomatoes", label: "Fire roasted tomatoes" },
  { value: "fish", label: "Fish" },
  { value: "fish sauce", label: "Fish sauce" },
  { value: "fish stock", label: "Fish stock" },
  { value: "flank steak", label: "Flank steak" },
  { value: "flax seeds", label: "Flax seeds" },
  { value: "fleur de sel", label: "Fleur de sel" },
  { value: "flour", label: "Flour" },
  { value: "flour tortillas", label: "Flour tortillas" },
  { value: "fontina cheese", label: "Fontina cheese" },
  { value: "food dye", label: "Food dye" },
  { value: "frank's redhot sauce", label: "Frank's redhot sauce" },
  { value: "free range eggs", label: "Free range eggs" },
  { value: "french bread", label: "French bread" },
  { value: "fresh basil", label: "Fresh basil" },
  { value: "fresh bean sprouts", label: "Fresh bean sprouts" },
  { value: "fresh chives", label: "Fresh chives" },
  { value: "fresh corn", label: "Fresh corn" },
  { value: "fresh corn kernels", label: "Fresh corn kernels" },
  { value: "fresh figs", label: "Fresh figs" },
  { value: "fresh fruit", label: "Fresh fruit" },
  { value: "fresh herbs", label: "Fresh herbs" },
  { value: "fresh mint", label: "Fresh mint" },
  { value: "fresh mozzarella", label: "Fresh mozzarella" },
  { value: "fresh rosemary", label: "Fresh rosemary" },
  { value: "fresh thyme leaves", label: "Fresh thyme leaves" },
  { value: "fried onions", label: "Fried onions" },
  { value: "frosting", label: "Frosting" },
  { value: "froyo bars", label: "Froyo bars" },
  { value: "frozen corn", label: "Frozen corn" },
  { value: "frozen spinach", label: "Frozen spinach" },
  { value: "fudge", label: "Fudge" },
  { value: "fudge topping", label: "Fudge topping" },
  { value: "fun size almond joy bar", label: "Fun size almond joy bar" },
  { value: "garam masala", label: "Garam masala" },
  { value: "garbanzo bean flour", label: "Garbanzo bean flour" },
  { value: "garlic", label: "Garlic" },
  { value: "garlic paste", label: "Garlic paste" },
  { value: "garlic powder", label: "Garlic powder" },
  { value: "garlic powder", label: "Garlic powder" },
  { value: "garlic salt", label: "Garlic salt" },
  { value: "gelatin", label: "Gelatin" },
  { value: "gf chocolate cake mix", label: "Gf chocolate cake mix" },
  { value: "gin", label: "Gin" },
  { value: "ginger", label: "Ginger" },
  { value: "ginger ale", label: "Ginger ale" },
  { value: "ginger paste", label: "Ginger paste" },
  { value: "ginger-garlic paste", label: "Ginger-garlic paste" },
  { value: "gingersnap cookies", label: "Gingersnap cookies" },
  { value: "gnocchi", label: "Gnocchi" },
  { value: "goat cheese", label: "Goat cheese" },
  { value: "golden raisins", label: "Golden raisins" },
  { value: "gorgonzola", label: "Gorgonzola" },
  { value: "gouda cheese", label: "Gouda cheese" },
  { value: "graham cracker crumbs", label: "Graham cracker crumbs" },
  { value: "graham cracker pie crust", label: "Graham cracker pie crust" },
  { value: "graham crackers", label: "Graham crackers" },
  { value: "grain blend", label: "Grain blend" },
  { value: "grand marnier", label: "Grand marnier" },
  { value: "granny smith apples", label: "Granny smith apples" },
  { value: "granola", label: "Granola" },
  { value: "granulated garlic", label: "Granulated garlic" },
  { value: "grape tomatoes", label: "Grape tomatoes" },
  { value: "grapefruit", label: "Grapefruit" },
  { value: "grapeseed oil", label: "Grapeseed oil" },
  { value: "gravy", label: "Gravy" },
  { value: "great northern beans", label: "Great northern beans" },
  { value: "greek yogurt", label: "Greek yogurt" },
  { value: "green beans", label: "Green beans" },
  { value: "green bell pepper", label: "Green bell pepper" },
  { value: "green chili pepper", label: "Green chili pepper" },
  { value: "green food coloring", label: "Green food coloring" },
  { value: "green grapes", label: "Green grapes" },
  { value: "green olives", label: "Green olives" },
  { value: "green onions", label: "Green onions" },
  { value: "greens", label: "Greens" },
  { value: "grill cheese", label: "Grill cheese" },
  { value: "grill seasoning", label: "Grill seasoning" },
  { value: "ground allspice", label: "Ground allspice" },
  { value: "ground ancho chili", label: "Ground ancho chili" },
  { value: "ground beef", label: "Ground beef" },
  { value: "ground chicken", label: "Ground chicken" },
  {
    value: "ground chipotle chile pepper",
    label: "Ground chipotle chile pepper",
  },
  { value: "ground cinnamon", label: "Ground cinnamon" },
  { value: "ground cinnamon", label: "Ground cinnamon" },
  { value: "ground cloves", label: "Ground cloves" },
  { value: "ground coriander seeds", label: "Ground coriander seeds" },
  { value: "ground cumin", label: "Ground cumin" },
  { value: "ground flaxseed", label: "Ground flaxseed" },
  { value: "ground ginger", label: "Ground ginger" },
  { value: "ground lamb", label: "Ground lamb" },
  { value: "ground mace", label: "Ground mace" },
  { value: "ground nutmeg", label: "Ground nutmeg" },
  { value: "ground pork", label: "Ground pork" },
  { value: "ground pork sausage", label: "Ground pork sausage" },
  { value: "ground veal", label: "Ground veal" },
  { value: "gruyere", label: "Gruyere" },
  { value: "guacamole", label: "Guacamole" },
  { value: "half n half", label: "Half n half" },
  { value: "halibut fillet", label: "Halibut fillet" },
  { value: "ham", label: "Ham" },
  { value: "hamburger buns", label: "Hamburger buns" },
  { value: "hard cooked eggs", label: "Hard cooked eggs" },
  { value: "harissa", label: "Harissa" },
  { value: "hash brown potatoes", label: "Hash brown potatoes" },
  { value: "hazelnuts", label: "Hazelnuts" },
  {
    value: "healthy request cream of celery soup",
    label: "Healthy request cream of celery soup",
  },
  { value: "hemp seeds", label: "Hemp seeds" },
  { value: "herbes de provence", label: "Herbes de provence" },
  { value: "herbs", label: "Herbs" },
  {
    value: "hershey's kisses brand milk chocolates",
    label: "Hershey's kisses brand milk chocolates",
  },
  { value: "hoisin sauce", label: "Hoisin sauce" },
  { value: "honey mustard", label: "Honey mustard" },
  { value: "horseradish", label: "Horseradish" },
  { value: "hot sauce", label: "Hot sauce" },
  { value: "hummus", label: "Hummus" },
  { value: "ice", label: "Ice" },
  { value: "ice cream", label: "Ice cream" },
  {
    value: "instant chocolate pudding mix",
    label: "Instant chocolate pudding mix",
  },
  { value: "instant coffee powder", label: "Instant coffee powder" },
  { value: "instant espresso powder", label: "Instant espresso powder" },
  { value: "instant lemon pudding mix", label: "Instant lemon pudding mix" },
  { value: "instant yeast", label: "Instant yeast" },
  { value: "irish cream", label: "Irish cream" },
  { value: "italian bread", label: "Italian bread" },
  { value: "italian cheese blend", label: "Italian cheese blend" },
  { value: "italian sausages", label: "Italian sausages" },
  { value: "italian seasoning", label: "Italian seasoning" },
  { value: "jaggery", label: "Jaggery" },
  { value: "jalapeno", label: "Jalapeno" },
  { value: "jasmine rice", label: "Jasmine rice" },
  { value: "jelly", label: "Jelly" },
  { value: "jicama", label: "Jicama" },
  { value: "jimmies", label: "Jimmies" },
  { value: "juice", label: "Juice" },
  { value: "jumbo shell pasta", label: "Jumbo shell pasta" },
  { value: "kaffir lime leaves", label: "Kaffir lime leaves" },
  { value: "kahlua", label: "Kahlua" },
  { value: "kalamata olives", label: "Kalamata olives" },
  { value: "kale", label: "Kale" },
  { value: "ketchup", label: "Ketchup" },
  { value: "kitchen bouquet", label: "Kitchen bouquet" },
  { value: "kiwis", label: "Kiwis" },
  { value: "kosher salt", label: "Kosher salt" },
  { value: "ladyfingers", label: "Ladyfingers" },
  { value: "lamb", label: "Lamb" },
  { value: "lasagna noodles", label: "Lasagna noodles" },
  { value: "lb cake", label: "Lb cake" },
  { value: "lean ground beef", label: "Lean ground beef" },
  { value: "lean ground turkey", label: "Lean ground turkey" },
  { value: "lean pork tenderloin", label: "Lean pork tenderloin" },
  { value: "leeks", label: "Leeks" },
  { value: "leg of lamb", label: "Leg of lamb" },
  { value: "lemon", label: "Lemon" },
  { value: "lemon curd", label: "Lemon curd" },
  { value: "lemon extract", label: "Lemon extract" },
  { value: "lemon juice", label: "Lemon juice" },
  { value: "lemon peel", label: "Lemon peel" },
  { value: "lemon pepper", label: "Lemon pepper" },
  { value: "lemon wedges", label: "Lemon wedges" },
  { value: "lemongrass", label: "Lemongrass" },
  { value: "lettuce", label: "Lettuce" },
  { value: "lettuce leaves", label: "Lettuce leaves" },
  { value: "light butter", label: "Light butter" },
  { value: "light coconut milk", label: "Light coconut milk" },
  { value: "light corn syrup", label: "Light corn syrup" },
  { value: "light cream cheese", label: "Light cream cheese" },
  { value: "light mayonnaise", label: "Light mayonnaise" },
  { value: "light olive oil", label: "Light olive oil" },
  { value: "light soy sauce", label: "Light soy sauce" },
  { value: "lime", label: "Lime" },
  { value: "lime juice", label: "Lime juice" },
  { value: "lime wedges", label: "Lime wedges" },
  { value: "lime zest", label: "Lime zest" },
  { value: "linguine", label: "Linguine" },
  { value: "liquid smoke", label: "Liquid smoke" },
  { value: "liquid stevia", label: "Liquid stevia" },
  { value: "liquor", label: "Liquor" },
  { value: "live lobster", label: "Live lobster" },
  { value: "long-grain rice", label: "Long-grain rice" },
  { value: "low fat buttermilk", label: "Low fat buttermilk" },
  { value: "low fat milk", label: "Low fat milk" },
  { value: "low fat milk", label: "Low fat milk" },
  { value: "low fat plain yogurt", label: "Low fat plain yogurt" },
  { value: "low fat ricotta cheese", label: "Low fat ricotta cheese" },
  { value: "low fat sour cream", label: "Low fat sour cream" },
  { value: "low sodium chicken broth", label: "Low sodium chicken broth" },
  { value: "low sodium soy sauce", label: "Low sodium soy sauce" },
  { value: "low-sodium chicken stock", label: "Low-sodium chicken stock" },
  { value: "lower sodium beef broth", label: "Lower sodium beef broth" },
  { value: "lump crab", label: "Lump crab" },
  { value: "m&m candies", label: "M&m candies" },
  { value: "macadamia nuts", label: "Macadamia nuts" },
  { value: "macaroni and cheese mix", label: "Macaroni and cheese mix" },
  { value: "madras curry powder", label: "Madras curry powder" },
  { value: "malt drink mix", label: "Malt drink mix" },
  { value: "mandarin orange sections", label: "Mandarin orange sections" },
  { value: "mandarin oranges", label: "Mandarin oranges" },
  { value: "mango", label: "Mango" },
  { value: "maple syrup", label: "Maple syrup" },
  { value: "maraschino cherries", label: "Maraschino cherries" },
  { value: "margarine", label: "Margarine" },
  { value: "marinara sauce", label: "Marinara sauce" },
  { value: "marjoram", label: "Marjoram" },
  { value: "marsala wine", label: "Marsala wine" },
  { value: "marshmallow fluff", label: "Marshmallow fluff" },
  { value: "marshmallows", label: "Marshmallows" },
  { value: "masa harina", label: "Masa harina" },
  { value: "mascarpone", label: "Mascarpone" },
  { value: "mat beans", label: "Mat beans" },
  { value: "matcha tea", label: "Matcha tea" },
  { value: "mayonnaise", label: "Mayonnaise" },
  { value: "meat", label: "Meat" },
  { value: "meat", label: "Meat" },
  { value: "meatballs", label: "Meatballs" },
  { value: "medjool dates", label: "Medjool dates" },
  { value: "mexican cream", label: "Mexican cream" },
  { value: "meyer lemon juice", label: "Meyer lemon juice" },
  { value: "milk", label: "Milk" },
  { value: "milk chocolate chips", label: "Milk chocolate chips" },
  { value: "mint chutney", label: "Mint chutney" },
  { value: "minute rice", label: "Minute rice" },
  { value: "miracle whip", label: "Miracle whip" },
  { value: "mirin", label: "Mirin" },
  { value: "miso", label: "Miso" },
  { value: "molasses", label: "Molasses" },
  { value: "monterey jack cheese", label: "Monterey jack cheese" },
  { value: "mushroom", label: "Mushroom" },
  { value: "mussels", label: "Mussels" },
  { value: "mustard", label: "Mustard" },
  { value: "mustard seeds", label: "Mustard seeds" },
  { value: "napa cabbage", label: "Napa cabbage" },
  { value: "navel oranges", label: "Navel oranges" },
  { value: "nectarine", label: "Nectarine" },
  { value: "new potatoes", label: "New potatoes" },
  { value: "non-fat greek yogurt", label: "Non-fat greek yogurt" },
  { value: "nonfat cool whip", label: "Nonfat cool whip" },
  { value: "nonfat milk", label: "Nonfat milk" },
  { value: "nori", label: "Nori" },
  { value: "nut butter", label: "Nut butter" },
  { value: "nut meal", label: "Nut meal" },
  { value: "nutella", label: "Nutella" },
  { value: "nutritional yeast", label: "Nutritional yeast" },
  { value: "oat flour", label: "Oat flour" },
  { value: "oats", label: "Oats" },
  { value: "oil", label: "Oil" },
  {
    value: "oil packed sun dried tomatoes",
    label: "Oil packed sun dried tomatoes",
  },
  { value: "okra", label: "Okra" },
  { value: "old bay seasoning", label: "Old bay seasoning" },
  { value: "olive oil", label: "Olive oil" },
  { value: "olives", label: "Olives" },
  { value: "onion", label: "Onion" },
  { value: "onion powder", label: "Onion powder" },
  { value: "onion soup mix", label: "Onion soup mix" },
  { value: "orange", label: "Orange" },
  { value: "orange bell pepper", label: "Orange bell pepper" },
  { value: "orange juice", label: "Orange juice" },
  { value: "orange juice concentrate", label: "Orange juice concentrate" },
  { value: "orange liqueur", label: "Orange liqueur" },
  { value: "orange marmalade", label: "Orange marmalade" },
  { value: "orange oil", label: "Orange oil" },
  { value: "orange zest", label: "Orange zest" },
  { value: "oregano", label: "Oregano" },
  { value: "oreo cookies", label: "Oreo cookies" },
  { value: "orzo", label: "Orzo" },
  { value: "oyster sauce", label: "Oyster sauce" },
  { value: "oysters", label: "Oysters" },
  { value: "palm sugar", label: "Palm sugar" },
  { value: "pancetta", label: "Pancetta" },
  { value: "paneer", label: "Paneer" },
  { value: "panko", label: "Panko" },
  { value: "papaya", label: "Papaya" },
  { value: "paprika", label: "Paprika" },
  { value: "parmigiano reggiano", label: "Parmigiano reggiano" },
  { value: "parsley", label: "Parsley" },
  { value: "parsley flakes", label: "Parsley flakes" },
  { value: "parsnip", label: "Parsnip" },
  {
    value: "part-skim mozzarella cheese",
    label: "Part-skim mozzarella cheese",
  },
  { value: "pasta", label: "Pasta" },
  { value: "pasta salad mix", label: "Pasta salad mix" },
  { value: "pasta sauce", label: "Pasta sauce" },
  { value: "pastry flour", label: "Pastry flour" },
  { value: "peach", label: "Peach" },
  { value: "peanut butter", label: "Peanut butter" },
  { value: "peanut butter chips", label: "Peanut butter chips" },
  { value: "peanut butter cups", label: "Peanut butter cups" },
  { value: "peanut oil", label: "Peanut oil" },
  { value: "peanuts", label: "Peanuts" },
  { value: "pear liqueur", label: "Pear liqueur" },
  { value: "pearl barley", label: "Pearl barley" },
  { value: "pearl onions", label: "Pearl onions" },
  { value: "peas", label: "Peas" },
  { value: "pecan", label: "Pecan" },
  { value: "pecan pieces", label: "Pecan pieces" },
  { value: "pecorino", label: "Pecorino" },
  { value: "penne", label: "Penne" },
  { value: "peperoncino", label: "Peperoncino" },
  { value: "pepper jack cheese", label: "Pepper jack cheese" },
  { value: "peppercorns", label: "Peppercorns" },
  { value: "peppermint baking chips", label: "Peppermint baking chips" },
  { value: "peppermint extract", label: "Peppermint extract" },
  { value: "pepperoni", label: "Pepperoni" },
  { value: "peppers", label: "Peppers" },
  { value: "pesto", label: "Pesto" },
  { value: "pickle relish", label: "Pickle relish" },
  { value: "pickles", label: "Pickles" },
  { value: "pico de gallo", label: "Pico de gallo" },
  { value: "pie crust", label: "Pie crust" },
  { value: "pimento stuffed olives", label: "Pimento stuffed olives" },
  { value: "pimientos", label: "Pimientos" },
  { value: "pine nuts", label: "Pine nuts" },
  { value: "pineapple", label: "Pineapple" },
  { value: "pineapple chunks", label: "Pineapple chunks" },
  { value: "pineapple in juice", label: "Pineapple in juice" },
  { value: "pineapple juice", label: "Pineapple juice" },
  { value: "pink himalayan salt", label: "Pink himalayan salt" },
  { value: "pinto beans", label: "Pinto beans" },
  { value: "pistachios", label: "Pistachios" },
  { value: "pita", label: "Pita" },
  { value: "pizza crust", label: "Pizza crust" },
  { value: "pizza mix", label: "Pizza mix" },
  { value: "plain greek yogurt", label: "Plain greek yogurt" },
  { value: "plain nonfat yogurt", label: "Plain nonfat yogurt" },
  { value: "plain yogurt", label: "Plain yogurt" },
  { value: "plantain", label: "Plantain" },
  { value: "plum", label: "Plum" },
  { value: "plum tomatoes", label: "Plum tomatoes" },
  { value: "poblano peppers", label: "Poblano peppers" },
  { value: "polenta", label: "Polenta" },
  { value: "polish sausage", label: "Polish sausage" },
  { value: "pomegranate juice", label: "Pomegranate juice" },
  { value: "pomegranate molasses", label: "Pomegranate molasses" },
  { value: "pomegranate seeds", label: "Pomegranate seeds" },
  { value: "popcorn", label: "Popcorn" },
  { value: "poppy seeds", label: "Poppy seeds" },
  { value: "pork", label: "Pork" },
  { value: "Pork & Beans", label: "Pork & Beans" },
  { value: "pork belly", label: "Pork belly" },
  { value: "pork butt", label: "Pork butt" },
  { value: "pork chops", label: "Pork chops" },
  { value: "pork links", label: "Pork links" },
  { value: "pork loin chops", label: "Pork loin chops" },
  { value: "pork loin roast", label: "Pork loin roast" },
  { value: "pork roast", label: "Pork roast" },
  { value: "pork shoulder", label: "Pork shoulder" },
  { value: "pork tenderloin", label: "Pork tenderloin" },
  { value: "port", label: "Port" },
  { value: "portabella mushrooms", label: "Portabella mushrooms" },
  { value: "pot roast", label: "Pot roast" },
  { value: "potato chips", label: "Potato chips" },
  { value: "potato starch", label: "Potato starch" },
  { value: "potatoes", label: "Potatoes" },
  { value: "poultry seasoning", label: "Poultry seasoning" },
  { value: "powdered sugar", label: "Powdered sugar" },
  { value: "pretzel sandwiches", label: "Pretzel sandwiches" },
  { value: "processed american cheese", label: "Processed american cheese" },
  { value: "prosciutto", label: "Prosciutto" },
  { value: "provolone cheese", label: "Provolone cheese" },
  { value: "prunes", label: "Prunes" },
  { value: "puff pastry", label: "Puff pastry" },
  { value: "pumpkin", label: "Pumpkin" },
  { value: "pumpkin pie filling", label: "Pumpkin pie filling" },
  { value: "pumpkin pie spice", label: "Pumpkin pie spice" },
  { value: "pumpkin puree", label: "Pumpkin puree" },
  { value: "pumpkin seeds", label: "Pumpkin seeds" },
  { value: "queso fresco", label: "Queso fresco" },
  { value: "quick cooking oats", label: "Quick cooking oats" },
  { value: "quinoa", label: "Quinoa" },
  { value: "quinoa flour", label: "Quinoa flour" },
  { value: "radicchio", label: "Radicchio" },
  { value: "radishes", label: "Radishes" },
  { value: "raisins", label: "Raisins" },
  { value: "rajma masala", label: "Rajma masala" },
  { value: "ramen noodles", label: "Ramen noodles" },
  { value: "ranch dressing", label: "Ranch dressing" },
  { value: "ranch dressing mix", label: "Ranch dressing mix" },
  { value: "raspberries", label: "Raspberries" },
  { value: "raspberry jam", label: "Raspberry jam" },
  { value: "raw cashews", label: "Raw cashews" },
  { value: "raw shrimp", label: "Raw shrimp" },
  {
    value: "ready-to-serve Asian fried rice",
    label: "Ready-to-serve Asian fried rice",
  },
  { value: "real bacon recipe pieces", label: "Real bacon recipe pieces" },
  { value: "red apples", label: "Red apples" },
  { value: "red bell peppers", label: "Red bell peppers" },
  { value: "red cabbage", label: "Red cabbage" },
  { value: "red chilli", label: "Red chilli" },
  { value: "red delicious apples", label: "Red delicious apples" },
  { value: "red food coloring", label: "Red food coloring" },
  { value: "red grapefruit juice", label: "Red grapefruit juice" },
  { value: "red grapes", label: "Red grapes" },
  { value: "red kidney beans", label: "Red kidney beans" },
  { value: "red lentils", label: "Red lentils" },
  { value: "red onion", label: "Red onion" },
  { value: "red pepper flakes", label: "Red pepper flakes" },
  { value: "red pepper powder", label: "Red pepper powder" },
  { value: "red potatoes", label: "Red potatoes" },
  { value: "red velvet cookie", label: "Red velvet cookie" },
  { value: "red wine", label: "Red wine" },
  { value: "red wine vinegar", label: "Red wine vinegar" },
  {
    value: "reduced fat shredded cheddar cheese",
    label: "Reduced fat shredded cheddar cheese",
  },
  { value: "refried beans", label: "Refried beans" },
  {
    value: "refrigerated crescent rolls",
    label: "Refrigerated crescent rolls",
  },
  { value: "refrigerated pizza dough", label: "Refrigerated pizza dough" },
  {
    value: "refrigerated sugar cookie dough",
    label: "Refrigerated sugar cookie dough",
  },
  { value: "rhubarb", label: "Rhubarb" },
  { value: "rib tips", label: "Rib tips" },
  { value: "rice", label: "Rice" },
  { value: "rice flour", label: "Rice flour" },
  { value: "rice krispies cereal", label: "Rice krispies cereal" },
  { value: "rice milk", label: "Rice milk" },
  { value: "rice noodles", label: "Rice noodles" },
  { value: "rice paper", label: "Rice paper" },
  { value: "rice syrup", label: "Rice syrup" },
  { value: "rice vinegar", label: "Rice vinegar" },
  { value: "rice wine", label: "Rice wine" },
  { value: "ricotta salata", label: "Ricotta salata" },
  { value: "ritz crackers", label: "Ritz crackers" },
  { value: "roast beef", label: "Roast beef" },
  { value: "roasted chicken", label: "Roasted chicken" },
  { value: "roasted nuts", label: "Roasted nuts" },
  { value: "roasted peanuts", label: "Roasted peanuts" },
  { value: "roasted red peppers", label: "Roasted red peppers" },
  { value: "roma tomatoes", label: "Roma tomatoes" },
  { value: "romaine lettuce", label: "Romaine lettuce" },
  { value: "root vegetables", label: "Root vegetables" },
  { value: "rosemary", label: "Rosemary" },
  { value: "rotini pasta", label: "Rotini pasta" },
  { value: "rotisserie chicken", label: "Rotisserie chicken" },
  { value: "round steak", label: "Round steak" },
  { value: "rub", label: "Rub" },
  { value: "rum extract", label: "Rum extract" },
  { value: "runny honey", label: "Runny honey" },
  { value: "russet potatoes", label: "Russet potatoes" },
  { value: "rutabaga", label: "Rutabaga" },
  { value: "rye bread", label: "Rye bread" },
  { value: "rye meal", label: "Rye meal" },
  { value: "saffron threads", label: "Saffron threads" },
  { value: "sage", label: "Sage" },
  { value: "sage leaves", label: "Sage leaves" },
  { value: "salad dressing", label: "Salad dressing" },
  { value: "salami", label: "Salami" },
  { value: "salmon fillet", label: "Salmon fillet" },
  { value: "salsa", label: "Salsa" },
  { value: "salsa verde", label: "Salsa verde" },
  { value: "salt", label: "Salt" },
  { value: "salt and pepper", label: "Salt and pepper" },
  { value: "salted butter", label: "Salted butter" },
  { value: "saltine crackers", label: "Saltine crackers" },
  { value: "sandwich bun", label: "Sandwich bun" },
  { value: "sauerkraut", label: "Sauerkraut" },
  { value: "sausage", label: "Sausage" },
  { value: "sausage links", label: "Sausage links" },
  { value: "scotch bonnet chili", label: "Scotch bonnet chili" },
  { value: "sea salt", label: "Sea salt" },
  { value: "sea scallops", label: "Sea scallops" },
  { value: "seasoned bread crumbs", label: "Seasoned bread crumbs" },
  { value: "seasoned rice vinegar", label: "Seasoned rice vinegar" },
  { value: "seasoned salt", label: "Seasoned salt" },
  { value: "seasoning", label: "Seasoning" },
  { value: "seasoning blend", label: "Seasoning blend" },
  { value: "seeds", label: "Seeds" },
  { value: "self-rising flour", label: "Self-rising flour" },
  { value: "semi sweet chocolate chips", label: "Semi sweet chocolate chips" },
  { value: "serrano chile", label: "Serrano chile" },
  { value: "sesame oil", label: "Sesame oil" },
  { value: "sesame seed hamburger buns", label: "Sesame seed hamburger buns" },
  { value: "sesame seeds", label: "Sesame seeds" },
  { value: "shallot", label: "Shallot" },
  { value: "sharp cheddar cheese", label: "Sharp cheddar cheese" },
  { value: "sheeps milk cheese", label: "Sheeps milk cheese" },
  { value: "shells", label: "Shells" },
  { value: "sherry", label: "Sherry" },
  { value: "sherry", label: "Sherry" },
  { value: "sherry vinegar", label: "Sherry vinegar" },
  { value: "shiitake mushroom caps", label: "Shiitake mushroom caps" },
  { value: "short grain rice", label: "Short grain rice" },
  { value: "short pasta", label: "Short pasta" },
  { value: "short ribs", label: "Short ribs" },
  { value: "shortbread cookies", label: "Shortbread cookies" },
  { value: "shortcrust pastry", label: "Shortcrust pastry" },
  { value: "shortening", label: "Shortening" },
  { value: "shredded cheddar cheese", label: "Shredded cheddar cheese" },
  { value: "shredded cheese", label: "Shredded cheese" },
  { value: "shredded chicken", label: "Shredded chicken" },
  { value: "shredded coconut", label: "Shredded coconut" },
  {
    value: "shredded mexican cheese blend",
    label: "Shredded mexican cheese blend",
  },
  {
    value: "shredded mexican cheese blend",
    label: "Shredded mexican cheese blend",
  },
  { value: "shredded mozzarella", label: "Shredded mozzarella" },
  { value: "silken tofu", label: "Silken tofu" },
  { value: "sirloin steak", label: "Sirloin steak" },
  { value: "skim milk ricotta", label: "Skim milk ricotta" },
  { value: "skim vanilla greek yogurt", label: "Skim vanilla greek yogurt" },
  {
    value: "skin-on bone-in chicken leg quarters",
    label: "Skin-on bone-in chicken leg quarters",
  },
  {
    value: "skinless boneless chicken breast halves",
    label: "Skinless boneless chicken breast halves",
  },
  {
    value: "skinless boneless chicken thighs",
    label: "Skinless boneless chicken thighs",
  },
  { value: "skinned black gram", label: "Skinned black gram" },
  { value: "slaw dressing", label: "Slaw dressing" },
  { value: "slaw mix", label: "Slaw mix" },
  { value: "slivered almonds", label: "Slivered almonds" },
  { value: "smoked paprika", label: "Smoked paprika" },
  { value: "smoked salmon", label: "Smoked salmon" },
  { value: "smoked sausage", label: "Smoked sausage" },
  { value: "smooth peanut butter", label: "Smooth peanut butter" },
  { value: "snapper fillets", label: "Snapper fillets" },
  { value: "snow peas", label: "Snow peas" },
  { value: "soda water", label: "Soda water" },
  { value: "sour cream", label: "Sour cream" },
  { value: "sourdough bowl", label: "Sourdough bowl" },
  { value: "sourdough bread", label: "Sourdough bread" },
  { value: "soy milk", label: "Soy milk" },
  { value: "soy protein powder", label: "Soy protein powder" },
  { value: "soy sauce", label: "Soy sauce" },
  { value: "spaghetti", label: "Spaghetti" },
  { value: "spaghetti squash", label: "Spaghetti squash" },
  { value: "sparkling wine", label: "Sparkling wine" },
  { value: "spelt flour", label: "Spelt flour" },
  { value: "spicy brown mustard", label: "Spicy brown mustard" },
  { value: "spinach", label: "Spinach" },
  { value: "sprite", label: "Sprite" },
  { value: "sprouts", label: "Sprouts" },
  { value: "squash", label: "Squash" },
  { value: "sriracha sauce", label: "Sriracha sauce" },
  { value: "steaks", label: "Steaks" },
  { value: "steel cut oats", label: "Steel cut oats" },
  { value: "stevia", label: "Stevia" },
  { value: "stew meat", label: "Stew meat" },
  { value: "stew vegetables", label: "Stew vegetables" },
  { value: "stock", label: "Stock" },
  { value: "store-bought phyllo", label: "Store-bought phyllo" },
  { value: "stout", label: "Stout" },
  { value: "strawberries", label: "Strawberries" },
  { value: "strawberry jam", label: "Strawberry jam" },
  { value: "strawberry jello", label: "Strawberry jello" },
  { value: "stuffing", label: "Stuffing" },
  { value: "stuffing mix", label: "Stuffing mix" },
  { value: "sub rolls", label: "Sub rolls" },
  { value: "sugar", label: "Sugar" },
  { value: "sugar snap peas", label: "Sugar snap peas" },
  { value: "sugar syrup", label: "Sugar syrup" },
  { value: "sukrin sweetener", label: "Sukrin sweetener" },
  { value: "summer savory", label: "Summer savory" },
  { value: "summer squash", label: "Summer squash" },
  { value: "sunflower oil", label: "Sunflower oil" },
  { value: "sunflower seeds", label: "Sunflower seeds" },
  { value: "sweet chilli sauce", label: "Sweet chilli sauce" },
  { value: "sweet onion", label: "Sweet onion" },
  { value: "sweet paprika", label: "Sweet paprika" },
  { value: "sweet pickle juice", label: "Sweet pickle juice" },
  { value: "sweet pickle relish", label: "Sweet pickle relish" },
  { value: "sweet potato", label: "Sweet potato" },
  { value: "sweet tea", label: "Sweet tea" },
  { value: "sweetened coconut", label: "Sweetened coconut" },
  { value: "sweetened condensed milk", label: "Sweetened condensed milk" },
  { value: "sweetened shredded coconut", label: "Sweetened shredded coconut" },
  { value: "swiss chard", label: "Swiss chard" },
  { value: "swiss cheese", label: "Swiss cheese" },
  { value: "taco seasoning mix", label: "Taco seasoning mix" },
  { value: "taco shells", label: "Taco shells" },
  { value: "tahini", label: "Tahini" },
  { value: "tamari", label: "Tamari" },
  { value: "tapioca flour", label: "Tapioca flour" },
  { value: "tarragon", label: "Tarragon" },
  { value: "tart apple", label: "Tart apple" },
  { value: "tea bags", label: "Tea bags" },
  { value: "tequila", label: "Tequila" },
  { value: "teriyaki sauce", label: "Teriyaki sauce" },
  { value: "thai basil", label: "Thai basil" },
  { value: "thai chiles", label: "Thai chiles" },
  { value: "thai red curry paste", label: "Thai red curry paste" },
  { value: "thick-cut bacon", label: "Thick-cut bacon" },
  { value: "tilapia fillets", label: "Tilapia fillets" },
  { value: "toast", label: "Toast" },
  { value: "toffee bits", label: "Toffee bits" },
  { value: "tofu", label: "Tofu" },
  { value: "tomatillos", label: "Tomatillos" },
  { value: "tomato juice", label: "Tomato juice" },
  { value: "tomato paste", label: "Tomato paste" },
  { value: "tomato puree", label: "Tomato puree" },
  { value: "tomato sauce", label: "Tomato sauce" },
  { value: "tomato soup", label: "Tomato soup" },
  { value: "tomatoes", label: "Tomatoes" },
  { value: "top blade steak", label: "Top blade steak" },
  { value: "top round steak", label: "Top round steak" },
  { value: "Top Sirloin", label: "Top Sirloin" },
  { value: "tortilla", label: "Tortilla" },
  { value: "tortilla chips", label: "Tortilla chips" },
  { value: "triple sec", label: "Triple sec" },
  { value: "truffle oil", label: "Truffle oil" },
  { value: "tuna", label: "Tuna" },
  { value: "turbinado sugar", label: "Turbinado sugar" },
  { value: "turkey", label: "Turkey" },
  { value: "turkey breast", label: "Turkey breast" },
  { value: "turkey kielbasa", label: "Turkey kielbasa" },
  { value: "turmeric", label: "Turmeric" },
  { value: "turnips", label: "Turnips" },
  { value: "unbleached flour", label: "Unbleached flour" },
  { value: "unsalted butter", label: "Unsalted butter" },
  { value: "unsmoked back bacon", label: "Unsmoked back bacon" },
  { value: "unsweetened applesauce", label: "Unsweetened applesauce" },
  { value: "unsweetened coconut milk", label: "Unsweetened coconut milk" },
  {
    value: "unsweetened shredded coconut",
    label: "Unsweetened shredded coconut",
  },
  { value: "vanilla bean", label: "Vanilla bean" },
  { value: "vanilla bean paste", label: "Vanilla bean paste" },
  { value: "vanilla essence", label: "Vanilla essence" },
  { value: "vanilla extract", label: "Vanilla extract" },
  { value: "vanilla frosting", label: "Vanilla frosting" },
  { value: "vanilla protein powder", label: "Vanilla protein powder" },
  { value: "vanilla wafers", label: "Vanilla wafers" },
  { value: "vanilla yogurt", label: "Vanilla yogurt" },
  { value: "vegan cheese", label: "Vegan cheese" },
  { value: "vegan chocolate chips", label: "Vegan chocolate chips" },
  { value: "vegan margarine", label: "Vegan margarine" },
  { value: "vegetable broth", label: "Vegetable broth" },
  { value: "vegetable oil", label: "Vegetable oil" },
  { value: "vegetarian bacon", label: "Vegetarian bacon" },
  { value: "vermouth", label: "Vermouth" },
  { value: "vinaigrette", label: "Vinaigrette" },
  { value: "vinegar", label: "Vinegar" },
  { value: "vodka", label: "Vodka" },
  { value: "walnuts", label: "Walnuts" },
  { value: "water", label: "Water" },
  { value: "water chestnuts", label: "Water chestnuts" },
  { value: "water-packed tuna", label: "Water-packed tuna" },
  { value: "watercress", label: "Watercress" },
  { value: "watermelon chunks", label: "Watermelon chunks" },
  { value: "wheat bran", label: "Wheat bran" },
  { value: "wheat germ", label: "Wheat germ" },
  { value: "whipped cream", label: "Whipped cream" },
  { value: "whipped topping", label: "Whipped topping" },
  { value: "whipping cream", label: "Whipping cream" },
  { value: "whiskey", label: "Whiskey" },
  { value: "white balsamic vinegar", label: "White balsamic vinegar" },
  { value: "white bread", label: "White bread" },
  { value: "white cake mix", label: "White cake mix" },
  { value: "white cheddar", label: "White cheddar" },
  { value: "white chocolate", label: "White chocolate" },
  { value: "white chocolate chips", label: "White chocolate chips" },
  { value: "white onion", label: "White onion" },
  { value: "white pepper", label: "White pepper" },
  { value: "white whole wheat flour", label: "White whole wheat flour" },
  { value: "white wine", label: "White wine" },
  { value: "white wine vinegar", label: "White wine vinegar" },
  { value: "whole allspice berries", label: "Whole allspice berries" },
  { value: "whole chicken", label: "Whole chicken" },
  { value: "whole coriander seeds", label: "Whole coriander seeds" },
  { value: "whole cranberry sauce", label: "Whole cranberry sauce" },
  { value: "whole kernel corn", label: "Whole kernel corn" },
  { value: "whole star anise", label: "Whole star anise" },
  { value: "whole wheat bread", label: "Whole wheat bread" },
  { value: "whole wheat flour", label: "Whole wheat flour" },
  { value: "whole wheat tortillas", label: "Whole wheat tortillas" },
  { value: "whole-grain mustard", label: "Whole-grain mustard" },
  { value: "wine", label: "Wine" },
  { value: "wine vinegar", label: "Wine vinegar" },
  { value: "winter squash", label: "Winter squash" },
  { value: "worcestershire sauce", label: "Worcestershire sauce" },
  { value: "xanthan gum", label: "Xanthan gum" },
  { value: "yeast", label: "Yeast" },
  { value: "yellow onion", label: "Yellow onion" },
  { value: "yogurt", label: "Yogurt" },
];
